name: gym
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - ca-certificates=2023.11.17=hbcca054_0
  - comm=0.1.4=pyhd8ed1ab_0
  - debugpy=1.8.0=py39h3d6467e_1
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - importlib-metadata=7.0.0=pyha770c72_0
  - importlib_metadata=7.0.0=hd8ed1ab_0
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py39hf3d152e_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgomp=13.2.0=h807b86a_3
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - openssl=3.2.0=hd590300_1
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py39h06a4308_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - psutil=5.9.7=py39hd1e30aa_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.9.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pyzmq=25.1.2=py39h8c080ef_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.3=py39hd1e30aa_1
  - traitlets=5.14.0=pyhd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.0.0
      - astunparse==1.6.3
      - box2d-py==2.3.5
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - decorator==4.4.2
      - farama-notifications==0.0.4
      - filelock==3.9.0
      - flatbuffers==23.5.26
      - fonttools==4.46.0
      - fsspec==2023.4.0
      - gast==0.5.4
      - google-auth==2.25.2
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.60.0
      - gymnasium==0.29.1
      - h5py==3.10.0
      - idna==3.6
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - importlib-resources==6.1.1
      - jinja2==3.1.2
      - keras==2.15.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - ml-dtypes==0.2.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - networkx==3.0
      - numpy==1.26.2
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pexpect==4.9.0
      - pillow==9.3.0
      - proglog==0.1.10
      - prompt-toolkit==3.0.43
      - protobuf==4.23.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pygame==2.5.2
      - pyglet==2.0.10
      - pyparsing==3.1.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - stack-data==0.6.3
      - swig==4.1.1.post1
      - sympy==1.12
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - torch==2.1.2+cu118
      - torchaudio==2.1.2+cu118
      - torchvision==0.16.2+cu118
      - tqdm==4.66.1
      - triton==2.1.0
      - typeguard==4.1.5
      - urllib3==2.1.0
      - werkzeug==3.0.1
      - wrapt==1.14.1
prefix: /home/takud/miniconda3/envs/gym
